config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :readings do
    get 'data', on: :collection
  end
  authenticated :user do
    root to: 'readings#index', as: :authenticated_root
  end
  root to: redirect('/users/sign_in')

end

app/models/reading.rb
class Reading < ActiveRecord::Base
  belongs_to :user
  validate :reading_within_allowable_range

  def reading_within_allowable_range
    readings = Reading.where(user_id: self.user_id)
    if readings.count == 0 && self.reading > 0
      return true
    end
    record_before = readings
      .where("reading_date < '#{self.reading_date}'")
      .order(:reading_date)
      .last
    record_after = readings
      .where("reading_date > '#{self.reading_date}'")
      .order(:reading_date)
      .first
    too_low = !record_before.nil? && (self.reading < record_before.reading)
    too_high = !record_after.nil? && (self.reading > record_after.reading)
    negative = self.reading < 0
    if too_low || too_high || negative
      errors.add(:reading, 'is not within allowable range')
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :readings, dependent: :destroy
  validates_presence_of :username
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/readings_controller.rb
require 'will_paginate/array'

class ReadingsController < ApplicationController
  before_action :set_all_readings, only: [:index, :data]
  before_action :set_reading, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def calculate_cost
    if @all_readings == nil
      cost = nil
    elsif @all_readings.length == 1
      cost = [0]
    else
      cost = @all_readings.each_cons(2).map { |a,b| ((b.reading-a.reading) * 0.28).round(2) }.unshift(0)
    end
  end

  # GET /readings
  # GET /readings.json
  def index
    @some_readings = @all_readings.paginate(:page => params[:page], :per_page => 10)
  end

  # GET /readings/1
  # GET /readings/1.json
  def show
  end

  # GET /readings/new
  def new
    @reading = current_user.readings.build
  end

  # GET /readings/1/edit
  def edit
  end

  # POST /readings
  # POST /readings.json
  def create
    # @new_params = reading_params.merge(:cost => Reading.cost_calculation(current_user, params['reading']['reading']))
    @reading = current_user.readings.build(reading_params)
    respond_to do |format|
      if @reading.save
        format.html { redirect_to @reading, notice: 'Reading was successfully created.' }
        format.json { render :show, status: :created, location: @reading }
      else
        format.html { render :new }
        format.json { render json: @reading.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /readings/1
  # PATCH/PUT /readings/1.json
  def update
    respond_to do |format|
      if @reading.update(reading_params)
        format.html { redirect_to @reading, notice: 'Reading was successfully updated.' }
        format.json { render :show, status: :ok, location: @reading }
      else
        format.html { render :edit }
        format.json { render json: @reading.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /readings/1
  # DELETE /readings/1.json
  def destroy
    @reading.destroy
    respond_to do |format|
      format.html { redirect_to readings_url, notice: 'Reading was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reading
      @reading = Reading.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reading_params
      params.require(:reading).permit(:reading, :reading_date)
    end

    def set_all_readings
      @all_readings = current_user.readings.order(reading_date: :asc)
      @all_readings = @all_readings.zip(calculate_cost)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:email, :password, :password_confirmation, :zip, :username)
  end

  def account_update_params
    params.require(:user).permit(:email, :password, :password_confirmation, :current_password, :zip, :username)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/readings_helper.rb
module ReadingsHelper
end

app/views/layouts/_navigation.html.erb
<!-- Navigation -->
<nav class="navbar navbar-default navbar-fixed-top" role="navigation" style="margin-bottom: 0">
  <div class="navbar-header">
    <a class="navbar-brand" href="/">Meter-Man</a>
  </div>
  <!-- /.navbar-header -->

  <ul class="nav navbar-top-links navbar-right">
  <% if user_signed_in? %>
    <li><p><%= current_user.username%></p>
    </li>
  <% end %>
    <li class="dropdown">
      <a class="dropdown-toggle" data-toggle="dropdown" href="#">
        <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
      </a>
      <ul class="dropdown-menu dropdown-user">
      <% if user_signed_in? %>
        <li>
          <%= link_to(destroy_user_session_path, :method => :delete) do %>
            <i class="fa fa-sign-out fa-fw"></i>
            Logout
          <% end %>
        </li>
        <li class="divider"></li>
        <li>
          <%= link_to(edit_user_registration_path) do %>
            <i class="fa fa-user fa-fw"></i>
            Edit Registration
          <% end %>
        </li>
      <% else %>
        <li>
          <%= link_to(new_user_session_path) do %>
            <i class="fa fa-sign-in fa-fw"></i>
            Login
          <% end %>
        </li>
        <li class="divider"></li>
        <li>
          <%= link_to(new_user_registration_path) do %>
            <i class="fa fa-user fa-fw"></i>
            Register
          <% end %>
        </li>
      <% end %>
      </ul>
      <!-- /.dropdown-user -->
    </li>
    <!-- /.dropdown -->
  </ul>
  <!-- /.navbar-top-links -->

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MeterMan</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <% if controller_name == 'readings' && action_name == 'index' %>
    <%= javascript_include_tag controller_name, 'data-turbolinks-track' => true %>
  <% end %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="wrapper">
    <%= render 'layouts/navigation' %>
    <div id="notifications">
      <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
      <% end %>
    </div>
    <div id="page-wrapper">
      <%= yield %>
    </div>
  </div>
</body>
</html>

app/views/readings/_form.html.erb
<%= form_for(@reading) do |f| %>
<% if @reading.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@reading.errors.count, "error") %> prohibited this reading from being saved:</h2>

    <ul>
    <% @reading.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="field">
  <%= f.label :reading %><br>
  <%= f.number_field :reading, placeholder: 'Reading' %>
</div> <br>
<div class="field">
  <%= f.label :reading_date %><br>
  <%= f.date_select :reading_date %>
</div> <br>
<div class="actions">
  <%= f.submit "Accept", class: 'btn btn-primary' %>
</div>
<% end %>

app/views/readings/edit.html.erb
<div class="form-devise">
    <h1>Editing Reading</h1>

  <%= render 'form' %>
  <hr>
  <%= link_to 'Show', @reading %><br>
  <%= link_to 'Back', readings_path %>
</div>

app/views/readings/index.html.erb
<div class="row">
  <div class="col-lg-12">
      <h1 class="page-header">Dashboard</h1>
  </div>
  <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<div class="row">
  <div class="col-lg-6">
    <div class="panel panel-default">
      <div class="panel-heading">
        <i class="fa fa-table fa-lg fa-fw"></i> Electricity Readings
        <div class="pull-right">
          <div class="btn-group">
            <%= button_to 'Add Reading', new_reading_path, method: :get, class: 'btn btn-primary btn-xs' %>
          </div>
        </div>
      </div>
      <!-- /.panel-heading -->
      <div class="panel-body">
        <div class="table-responsive">
          <table class="table table-bordered table-striped table-hover">
            <thead>
              <tr>
                <th>Date</th>
                <th>
                  <span class="table-tooltip" title="The value that your electricity meter displays. (Note: this number always increases)" data-toggle="reading-col-tooltip" data-placement="bottom">
                    Reading (kWh) <i class="fa fa-question-circle"></i>
                  </span>
                </th>
                <th>
                  <span class="table-tooltip" title="How much you spent on electricity during the interval between two reading dates." data-toggle="reading-col-tooltip" data-placement="bottom">
                    Cost <i class="fa fa-question-circle"></i>
                  </span>
                </th>
                <th colspan="3">Actions</th>
              </tr>
            </thead>
            <tbody>
              <% @some_readings.each do |reading, cost| %>
                <tr>
                  <td><%= reading.reading_date.strftime("%m-%d-%Y") %></td>
                  <td><%= number_with_delimiter(reading.reading, :delimiter => ',') %></td>
                  <td><%= number_to_currency(cost) %></td>
                  <td class="action"><%= link_to 'Show', reading %></td>
                  <td class="action"><%= link_to 'Edit', edit_reading_path(reading) %></td>
                  <td class="action"><%= link_to 'Destroy', reading, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        <!-- /.table-responsive -->
        <%= will_paginate @some_readings %>
      </div>
      <!-- /.panel-body -->
    </div>
    <!-- /.panel -->
  </div>
  <!-- /.col-lg-6 -->

  <div class="col-lg-6">
    <div class="panel panel-default">
      <div class="panel-heading">
        <i class="fa fa-line-chart fa-lg fa-fw"></i> Electricity Readings Plot
      </div>
      <!-- /.panel-heading -->
      <div class="panel-body">
        <svg id="line-plot"></svg>
      </div>
      <!-- /.panel-body -->
    </div>
    <!-- /.panel -->
  </div>
  <!-- /.col-lg-6 -->
</div>
<!-- /.row -->

app/views/readings/new.html.erb
<div class="form-devise">
  <h1>New Reading</h1>
  <%= render 'form' %>
  <hr>
  <%= link_to 'Back', readings_path %>
</div>

app/views/readings/show.html.erb
<div class="form-devise">
  <h2>Reading Details</h2>
  <p>
    <strong>Reading:</strong>
    <%= @reading.reading %>
  </p>

  <p>
    <strong>Reading date:</strong>
    <%= @reading.reading_date %>
  </p>
  <%= link_to 'Edit', edit_reading_path(@reading), class: 'btn btn-primary' %>
  <hr>
  <%= link_to 'Back', readings_path %>
</div>